### ISSUE TITLE
create a script with auto answer after sysypgrade

### ISSUE THREAD

**Issue by PerkelSimon** [lynxthecat/adblock-lean#124]
Hi, 

as discuted in the forum, after sysupgrade, we need to run `sh /etc/init.d/adblock-lean setup` as we can see here in the `read.me`

`After completing sysupgrade, run the interactive setup again to re-enable adblock-lean: sh /etc/init.d/adblock-lean setup. To preserve your old config, answer e when asked this question: Generate [n]ew config or use [e]xisting config?`

So is it possible to make a script to run `sh /etc/init.d/adblock-lean setup` + integrate the ''e'' as answer?
thanks

**Comment by lynxthecat** [comment]
Any thoughts on this @friendly-bits?

**Comment by friendly-bits** [comment]
In general, I think it's in the best interest of the user to manually issue the setup command after sysupgrade and monitor the output to make sure that no errors are encountered. Even assuming that we can persistently guarantee compatibility with future **generic** OpenWrt versions, adblock-lean integrates with dnsmasq which is a critical system service, and we do not control all the possible variables at play here. For example, some users may do sysupgrade to a customized openwrt build where dnsmasq does not behave in a way which we expect. Or, for another example, some other software running automatically on first boot may reset /etc/config/dhcp which may mess up adblock-lean.

So I'm a bit wary of having this functionality advertised as a supported feature because most users will not foresee the aforementioned implications.

That said, I do see the point of making sysupgrade easier for our users. Not really sure whether this outweighs the above considerations, though, especially considering that manually running 1 command and answering a few straightforward questions is not really tedious IMO.

**Comment by friendly-bits** [comment]
So what do you guys think? Personally, I'm in favor of not implementing this (for reason listed above), but I'm open to discussion.

**Comment by mktums** [comment]
Hi. 
Trying to automate my homelab's router setup with Ansible and stumbled upon lack of non-interactive mode for `gen-config` command. Using some hacks for now to make it work:

```yaml
- name: Generate default adblock-lean config (medium preset)
  community.openwrt.command:
    cmd: >-
      sh -c 'luci_preset=medium luci_upd_cron_job=1 luci_cron_schedule="{{ adblock_cron_schedule }}"
      DO_DIALOGS=0 service adblock-lean gen_config'
    creates: /etc/adblock-lean/config
  changed_when: true
```
